### ISSUE TITLE
Clarify path separator used in filename in the spec.

### ISSUE THREAD

**Issue by shurcooL** [campoy/embedmd#11]
The `embedmd` command is currently specified/documented as:

> The format of an embedmd command is:
> 
> ```
> [embedmd]:# (filename language /start regexp/ /end regexp/)
> ```
> 
> The embedded code will be extracted from the file filename, starting at the first line that matches /start regexp/ and finishing at the first line matching /end regexp/.

This is underspecified, and I have the following questions about the filename:
- Can the filename refer to a file inside a directory? If so, what should the path separator be used? Would it be the OS-specific path separator, such as `\` on Windows or `/` on Linux? Or would it always be slash (`/`, U+002F) separated like URLs are, no matter what OS you're on?
- Are absolute paths supported too, or only relative paths?

So, if I have a file `hello.go` in a subfolder `code`, which of these should I write if I'm on Windows:

``` Markdown
[embedmd]:# (code/hello.go /package.*/)
```

``` Markdown
[embedmd]:# (code\hello.go /package.*/)
```

~~Or is it invalid/unsupported to have the hello.go file inside a subfolder?~~ **Edit:** According to [this test case](https://github.com/campoy/embedmd/blob/1df02eb8cc14806032ec17bb3362c14d89109e19/main_test.go#L57-L58), subfolders are supported.

I think resolving this issue is a prerequisite for resolving #10.

Also, in case it's not obvious, I really hope you choose to go with always `/`-separated paths, because that's the only way Markdown documents written on any OS would be compatible/interchangeable.

**Comment by shurcooL** [comment]
Friendly ping. Is there anything unclear in this issue description? Can I help?

**Comment by shurcooL** [comment]
Friendly ping. I'll just quote the TLDR of the issue here, just in case that's helpful:

> Also, in case it's not obvious, I really hope you choose to go with always `/`-separated paths, because that's the only way Markdown documents written on any OS would be compatible/interchangeable.

**Comment by campoy** [comment]
I want to make sure that an Markdown file written on my Windows will work on any other platform.

To make sure this happens I propose to support:

- only relative paths: therefore removing the need of  `C:\` vs `/`
- only forward slashes '/': on Windows these will be converted to `\` before trying to open any file.

What do you think, @shurcooL ?

**Comment by shurcooL** [comment]
I think that sounds fantastic and that's exactly how I expected you to resolve this. Thanks.
