### ISSUE TITLE
It should be easy to match "to the next blank line"

### ISSUE THREAD

**Issue by dgryski** [campoy/embedmd#20]
An entry such as:

Given `input.txt`:
```
foo
bar
baz

qux
zot
```

With input:
`[embedmd]:# (input.txt /foo/ /\n\n/)`
embeds the text
```
foo
bar
baz

```
*including* the final blank line.

Obviously I could make the regexp match 'baz' instead, but I think wanting to embed chunks of lines should be easier.

**Comment by shurcooL** [comment]
Is there a resolution to this @dgryski? Would you mind sharing it here for posterity? Or did you give up on this need?

**Comment by dgryski** [comment]
Oh wow.  I thought I commented here.

The regexp ` /(?m:^$)/)` works to match to the next empty line.
