### ISSUE TITLE
sample/docs.md should not equal sample/result.md

### ISSUE THREAD

**Issue by jcscottiii** [campoy/embedmd#3]
This commit copied the output from embedmd into the original markdown file.

https://github.com/campoy/embedmd/commit/2e8f03cdc6db0e4fb3d2a87fe688edb4d2126197#diff-c7edd5db6ef267c552d8258e11683af6R6

It should only contain the markdown tags. Just need to revert the change in that file.

I can put up a PR tonight if someone else doesn't get to it.

**Comment by campoy** [comment]
Oops! Thanks, it's fixed now
