### ISSUE TITLE
Allow tabs to be rewritten to spaces

### ISSUE THREAD

**Issue by joncalhoun** [campoy/embedmd#31]
Tabs work great in code because we can set their width to whatever we prefer in our editor, but in blog posts they usually just lead to code running off the screen.

It would be cool if you could translate tabs to 2 spaces, or set a tab width somehow. Is this a PR you would be willing to consider?

**Comment by shurcooL** [comment]
Can another tool do this? If so, that'd be better and more unix-y.

**Comment by joncalhoun** [comment]
@shurcooL Good point. It looks like https://github.com/revin/markdown-it-expand-tabs would do the trick and wouldn't be hard to rewrite in Go if someone didn't want to install Node. 

Closing since this is unnecessary.
