### ISSUE TITLE
Unable to match escaped forward-slashes

### ISSUE THREAD

**Issue by bbrks** [campoy/embedmd#44]
I want to match between a set of multi-line C-style (`/*` `*/`) style comments which get displayed at the package level in the godoc tool. For example: [doc.go source](https://golang.org/src/encoding/gob/doc.go) -> [godoc preview](https://golang.org/pkg/encoding/gob/)

But I get an `unbalanced /` error when trying to escape values with the regexps: `/\/\*/` or `/\*\//`

I'd imagine this would also cause issues when attempting to match a file path, or URL.

**Comment by campoy** [comment]
Thanks for the issue, I disagree on your fix (see the comments on the PR) but I agree this should be fixed 👍

**Comment by bbrks** [comment]
I've addressed your comments, thanks!
