### ISSUE TITLE
Binary releases

### ISSUE THREAD

**Issue by jpillora** [campoy/embedmd#6]
> "if there's enough interest, I will provide binaries for every OS and architecture out there ... eventually."

You may be interested in [cloud-gox](https://github.com/jpillora/cloud-gox)

**Comment by campoy** [comment]
Hah, I built the same thing long time ago but couldn't release for security reasons.
Nice! 😄 

For how long are those binaries available? Could you provide a landing page per project so people can just go there and click on the platform they care about?

**Comment by jpillora** [comment]
No need! In addition to building to disk, it also uploads to Github
releases (E.g. https://github.com/jpillora/cloud-torrent/releases) see
README for details
https://github.com/jpillora/cloud-gox/blob/master/README.md

**Comment by campoy** [comment]
This has been fixed!

https://github.com/campoy/embedmd/releases
